### ISSUE TITLE
JS error on server-side updates

### ISSUE THREAD

**Issue by Giljjj** [benvp/live_motion#3]
https://github.com/benvp/live_motion/blob/d9f5616c15e12fbbdca7228c165613218c8142dc/priv/static/live_motion.js#L881

When settings a server-side attribute such as `rotate: @rotate`, upon update the `updated` function is called and the js throws an error: 
`Uncaught TypeError: this.animate is not a function`.

`animate()` does not exist. Changing `animate()` to `maybeAnimate()` seems to work.

**Comment by benvp** [comment]
Thanks for reporting this. Indeed I saw the same behaviour yesterday. I recently renamed the function and didn't rename the other one properly. Thats also one reason why I'm switching to TypeScript in the next release, which happens sometime next week. 

Additionally I still need to add tests. 😃
