### ISSUE TITLE
Passing class via opts to `LiveMotion.motion` component

### ISSUE THREAD

**Issue by oliverswitzer** [benvp/live_motion#7]
Hey again!

I was wondering if it was possible to style the wrapper div rendered by the `LiveMotion.motion` component via class selectors. The example below isn't working but I was imagining something like this: 

```
<LiveMotion.motion 
    class="absolute w-full z-10" 
    ...
/>
```

Or a solution to be more generic than just supporting `class`:

```
<LiveMotion.motion 
    opts={[class: "absolute w-full z-10", "some-other-attribute": "some-attribute-value"]} 
    ...
/>
```

**Comment by oliverswitzer** [comment]
🤦 this already works... My server wasn't reloading properly as I was testing this. Apologies for the false flag!

**Comment by benvp** [comment]
Hey @oliverswitzer. All good, I was just reading the issue and was thinking, that it should be possible already. However, stay tuned for LiveView 0.18.0 to be released - then we will have dynamic components where you can decide the element for the wrapper tag yourself :)
